version: "3.3"

services:
  mongodb-dev:
    image: mongo
    container_name: mymongodb-iy4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ABC123ssi
    ports:
      - "27017:27017"
    volumes:
      - ./home/mongodb:/home/mongodb
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db

  nodets-starterapp:
    build: .
    container_name: nodeStarter-iy
    restart: always
    depends_on:
      - mongodb-dev
    ports:
      - 5052:3000

volumes:
  mongodb_data:
    driver: local
